### ISSUE TITLE
add selection transformer based on the Information Value (IV) for nominal variables

### ISSUE THREAD

**Issue by SurajitTest** [feature-engine/feature_engine#280]
Presently, there are no packages in python to calculate Information Value using WOE for nominal/categorical variables. As WOE Encoder is already available in Feature Engine, hence I am raising the request for a feature to obtain information value  for nominal variables

**Comment by solegalli** [comment]
could you add a few links with information about WoE and IV?

**Comment by SurajitTest** [comment]
https://www.listendata.com/2015/03/weight-of-evidence-woe-and-information.html

https://www.listendata.com/2019/08/WOE-IV-Continuous-Dependent.html

http://ucanalytics.com/blogs/information-value-and-weight-of-evidencebanking-case/

**Comment by saurabhgoel1985** [comment]
Hi Sole, I am interested to work on this, but I dont not much idea about open source contribution. I have recently watched all your ML courses on Udemy and I really liked them, thats why I am inclined to take a shot at this. Can you guide me a little bit here.

**Comment by solegalli** [comment]
Welcome @saurabhgoel1985 

Absolutely! I look forward to working with you.

First of all, it's been a while since I read those articles on IV, so I guess, the first thing would be to go over them and maybe add a few bullet points below on what the new transformer should be doing.

From the top of my head, using the WoE we should replace the categories by the IV instead.

Then, since the IV, if I remember correctly is calculated with the WoE, maybe a good idea is to create a new transformer that inherits the WoEEncoder and calculates the IV. But again, this is high level, because I do not remember exaclty how to calculate the IV.

The encoder would go in a new python script that takes the name of the encoder, inside the folder feature_engine/encoding

I suggest you take a look at the WoEEncoder class that lives within that same folder, copy all the content into a new class in the new script, and edit according to the new transformer.

Have fun! And let me know if you need anything!

**Comment by solegalli** [comment]
Correction: the transformer is for feature selection, so I edited the former comment.

**Comment by Morgan-Sell** [comment]
I started working on this already. I not by my PC but there is a PR.

**Comment by saurabhgoel1985** [comment]
> Hey everyone, I apologize I forgot to write that PR #488 closes this PR. The PR is mentioned above.
> 
>  I’ve made some decent progress. I’m on vacation. I will continue to work on the PR when I return.
> 
> i believe that @solegalli has provided feedback that I need to incorporate.

Thanks for the update Morgan, hope the PR gets merged soon

**Comment by solegalli** [comment]
Sorry @Morgan-Sell I 've not reviewed that PR yet. You make so many PRs that I can't keep up :p 

I'll review the 2 remaining PRs on Wednesday.

Cheers
