### ISSUE TITLE
Feature_engine installed but can not import

### ISSUE THREAD

**Issue by Arminkhayati** [feature-engine/feature_engine#425]
HI

**Describe the bug**
I have tried and installed Feature_Engine 1.2 using both pip and conda install command but when I want to import it in my jupyter notebook it says 
`No module named 'feature_engine'`

I can verify that feature_engine is installed in my environment but when I run jupyter notebook and try to import it, that error rises. (And yes I am running jupyter notebook from the environment where feature_engine installed.)

![image](https://user-images.githubusercontent.com/25643788/164725331-cc72752a-81ff-4acc-a87e-c3d64c6af55f.png)

![image](https://user-images.githubusercontent.com/25643788/164725545-3cf6d659-8f89-4105-af03-3daa6dc7a7f8.png)

**Comment by solegalli** [comment]
Sorry for the delay, I was on holidays. 

A couple of sanity checks:

1. Did you change the kernel in the jupyter notebook to the environment in which feature-engine is installed? (from tab "Kernel" -> "change kernel")
2. Did you re-start the jupyter notebook kernel after installing feature engine?

From your message above I guess the answer to the above questions is yes. If that is the case, could you try installing a different library to the environment where you installed feature-engine? for example featuretools or Category-encoders and see if you can import those from the jupyter notebook?

I don't think this issue is related to feature-engine to be honest, I think it has to do with how the environment was ported to jupyter.

Let me know how it goes.

**Comment by Arminkhayati** [comment]
Thank you, I hope you had great time on holidays. 
I did what you said, installed those libraries and again I couldn't import them. You were right. so I tried reinstalling jupyter notebook and the problem solved. thank you.

**Comment by solegalli** [comment]
Glad you could solve the issue! :)

Will close this thread then.
