### ISSUE TITLE
Deal with KeyError when combine two or more selection transformers with the variables parameter.

### ISSUE THREAD

**Issue by Typepluto** [feature-engine/feature_engine#442]
When I try to combine two or more selection transformers(by sklearn pipeline) with the variables parameter.
Due to the first selection transformer already dropping some features, I would encounter KeyError.

For example:

I want to combine DropHighPSIFeatures(split by 'position') and DropHighPSIFeatures(split by 'date') selection transformer.
I don't want 'date'  and 'position' to compute by the other transformer, so I need to set variables for them.
Things are doing well when fitting the first transformer but get KeyError when fitting the second transformer.

I have two ideas:

1. Add an 'ignore_variables_not_exist'(or another name) bool parameter that can automatically
change the variables parameter to the intersection of variables parameter and columns of input data.

2. Add an 'exclude'(or another name) bool parameter that makes the variables parameter be excluded.

Not sure which one is best or if this feature is needed. I will start working on it if you think this is needed.

**Comment by solegalli** [comment]
Hi @Typepluto 

This issue was already raised here  #309 and resolved here  #369

From version 1.3 (released last Thursday) you can now use the parameter `confirm_variables` to tell the selector to adjust the list according to what is available in the incoming dataframe.

Check the new documentation here: https://feature-engine.readthedocs.io/en/latest/api_doc/selection/DropHighPSIFeatures.html

So if you pass to the first selector [var1, var2, var3] and the to the second [var2, var3, var4] and set confirm_variables=True, and say the first selector dropped var2, the second selector will adjust the list and work with var3 and var 4 only.

This new functionality was introduced by @gverbock  

Please try it out, let us know if it works, and if it does, it would be great if you could close the issue :)

**Comment by Typepluto** [comment]
Thank you for your reply!

I've tested `confirm_variables `it works as well as I thought.

Thank you for all your great work! :)
