### ISSUE TITLE
RecursiveFeatureElimination transformation doesn't work on a simple example

### ISSUE THREAD

**Issue by nyavramov** [feature-engine/feature_engine#620]
**Describe the bug**

A simple example that attempts to use this algorithm to select an important feature causes the RFE output to be an empty dataframe. The toy example below uses a variable "x", which is perfectly correlated with the target variable "y", along with a low-information feature "z", which would presumably be discarded. 

**To Reproduce**
```python
from feature_engine.selection import RecursiveFeatureElimination
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

df = pd.DataFrame(
    {
        "x": [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],  # Feature with 100% correlation with target variable
        "z": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],  # Feature with low-information, 0% correlation with target variable
        "y": [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],  # Target variable
    }
)

transformer = RecursiveFeatureElimination(estimator=linear_model, scoring="r2", cv=3)
output = transformer.fit_transform(df[['x', 'z']], df['y'])

print(output)
```

**Expected behavior**

I would expect the model to select column "x" rather than an empty dataframe. 

**Actual behavior**

```
/venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
3 fits failed out of a total of 3.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py", line 662, in fit
    X, y = self._validate_data(
  File "/venv/lib/python3.9/site-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 964, in check_X_y
    X = check_array(
  File "/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 665, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
  File "<__array_function__ internals>", line 180, in result_type
ValueError: at least one array or dtype is required

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
3 fits failed out of a total of 3.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/venv/lib/python3.9/site-packages/sklearn/linear_model/_base.py", line 662, in fit
    X, y = self._validate_data(
  File "/venv/lib/python3.9/site-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 964, in check_X_y
    X = check_array(
  File "/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 665, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
  File "<__array_function__ internals>", line 180, in result_type
ValueError: at least one array or dtype is required

  warnings.warn(some_fits_failed_message, FitFailedWarning)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```

**Desktop (please complete the following information):**

 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] 1.3.0

**Comment by TadayoshiCarvajal** [comment]
![image](https://user-images.githubusercontent.com/20735063/221965228-5ec3eb41-3baf-4582-9081-c741aa5c8378.png)

This issue seems to relate to the above snippet of code in the fit() method. By the second iteration of this loop, X_tmp only contains the 'x' feature since 'z' was dropped on the previous iteration. 

`X_tmp.drop(columns='x')`
Will result in an empty DataFrame. Then when we attempt to fit() on an empty DataFrame in the LinearRegression.fit(), we eventually get:

`ValueError: at least one array or dtype is required`

Perhaps the function should assume that the only remaining feature should be kept?
![image](https://user-images.githubusercontent.com/20735063/221966670-b0a27eba-1e7a-42fe-8f0e-aedd261d75f7.png)

Unfortunately, this will not address the scenario where the only remaining column is worthless (constant, noisy, etc.). Perhaps we can utilize the `self.feature_importances` for this. 

![image](https://user-images.githubusercontent.com/20735063/221967565-b218d56a-de99-433c-8b12-ed45341c90d7.png)

If there is any value to the final remaining feature deemed by the initial fit(), we can keep it, otherwise remove? Alternatively, we can compare the `feature_importances[feature]` value to the threshold itself or create some new kwarg?
![image](https://user-images.githubusercontent.com/20735063/221968085-152925fd-04e2-4066-8ae8-c75a2d221f30.png)

This way, we don't reach a situation where we attempt to fit the estimator on an empty DataFrame. Perhaps, there are better solutions -- hopefully the feature-engine team can offer feedback soon...

**Comment by solegalli** [comment]
Hey @TadayoshiCarvajal thanks for flagging where the problem was. And thanks @nyavramov for raising this issue. I wasn't aware of this.

I'd outsource the task of deciding if the model performance is good to the user (`baseline_model_performance`). I mean, generally, before selecting features, we would train a model with all features and evaluate its performance. If it is bad, doing feature selection does not make much sense, in my opinion.

For performance metrics like the ROC-AUC, it is kind of clear when a model is bad (0.5), for other metrics, like the accuracy or the mse, it is more up to the user. If the current model has 0 accuracy, then a model that has 1% is already a win, so it would be hard for us to contemplate all possibilities.

The easiest would be to stop the search when X_tmp has only 1 feature (like @TadayoshiCarvajal suggests) and maybe raise a warning saying, "Hey we had to stop the search because there's only 1 variable left in the dataframe. Please try alternative methods of feature selection / validation."

What do you think?

@TadayoshiCarvajal would you be up for making the code change? we could add @nyavramov example in the tests to ensure this no longer happens.
