### ISSUE TITLE
PRatioEncoder class is not searchable

### ISSUE THREAD

**Issue by Okroshiashvili** [feature-engine/feature_engine#630]
I found that **PRatioEncoder** class from encoding module does not exist anymore and still we try to import it in tests as well as there are records in docs about it.

I also checked Github issues and it's not mentioned anywhere. Please, have a look.

**Comment by solegalli** [comment]
We are deprecating PRatioEncoder as part of this release. 

I wanted to release last week, but we have several PRs going on, so I am waiting for those :)

The online docs show the current available version with this class. But if you build the docs locally, it should not appear. Otherwise let me know.

**Comment by Okroshiashvili** [comment]
Okay then. I was not aware of this ☺️ We can safely close this issue
